# Generated by Django 6.0.1 on 2026-02-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
