# Generated by Django 6.0.1 on 2026-02-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emoji_reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
            ],
            options={
                'unique_together': {('message', 'sender', 'emoji')},
            },
        ),
    ]
