# Generated by Django 6.0.1 on 2026-02-11 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_emoji_reactions_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emoji_reactions',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='chat.message'),
        ),
    ]
